USE db_aoa;

CREATE TABLE db_aoa.tb_usuarios(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    dt_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dt_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 

    CONSTRAINT UC_tb_usuarios UNIQUE (email),
    CONSTRAINT CHK_tb_usuarios CHECK (LENGTH(senha) >= 8)
);